language: clojure
lein: 2.7.1
script:
  - make ${CLOJURE_VERSION}-tests
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  # No reader conditionals for Clojure 1.5 or 1.6 ...
  #- CLOJURE_VERSION=clj15
  #- CLOJURE_VERSION=clj16
  - CLOJURE_VERSION=clj17
  - CLOJURE_VERSION=clj18
  #- CLOJURE_VERSION=clj19
notifications:
  email:
      - oubiwann@gmail.com
